server:
  port: 8002
spring:
  application:
    name: microservice-eureka-order
eureka:
  instance:
    prefer-ip-address: true #注册服务的时候使用服务的IP地址
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/