server:
  port: 8050
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: microservice-gateway-zuul
zuul:
  routes: #需要映射的路径
    microservice-eureka-order: /order/**
    miscroservice-eureka-user-hystrix: /findOrdersByUser/**